namespace Integracao.TOTVS.Winthor.Entitys.Entitys;

public class PcEst
{
    public string CODPROD { get; set; }
    public string CODFILIAL { get; set; }
    public string QTEST { get; set; }
    public string ESTMIN { get; set; }
    public string DTULTENT { get; set; }
    public string DTULTSAIDA { get; set; }
    public string QTVENDMES { get; set; }
    public string QTVENDMES1 { get; set; }
    public string QTVENDMES2 { get; set; }
    public string QTVENDMES3 { get; set; }
    public string QTPERDADIA { get; set; }
    public string QTPERDAMES { get; set; }
    public string VLVENDMES { get; set; }
    public string QTVENDDIA { get; set; }
    public string VLVENDDIA { get; set; }
    public string QTPEDIDA { get; set; }
    public string VLCUSTODIAREAL { get; set; }
    public string VLCUSTOMESREAL { get; set; }
    public string VLCUSTODIAFIN { get; set; }
    public string VLCUSTOMESFIN { get; set; }
    public string QTESTANT { get; set; }
    public string PCUSTOANT { get; set; }
    public string QTRESERV { get; set; }
    public string QTULTENT { get; set; }
    public string CUSTOULTENT { get; set; }
    public string QTESTGER { get; set; }
    public string QTENTDIA { get; set; }
    public string QTENTMES { get; set; }
    public string VLVENDDIAREAL { get; set; }
    public string VLVENDMESREAL { get; set; }
    public string CUSTOCONT { get; set; }
    public string QTBLOQUEADA { get; set; }
    public string FIMESTOQUE { get; set; }
    public string QTINDENIZ { get; set; }
    public string QTULTINVENT { get; set; }
    public string QTVENDAPERDIDA { get; set; }
    public string CUSTOREAL { get; set; }
    public string CUSTOFIN { get; set; }
    public string CUSTOREP { get; set; }
    public string VALORULTENT { get; set; }
    public string QTBLOQTRANSF { get; set; }
    public string QTPENDENTE { get; set; }
    public string QTVENDSEMANA { get; set; }
    public string QTVENDSEMANA1 { get; set; }
    public string QTVENDSEMANA2 { get; set; }
    public string QTVENDSEMANA3 { get; set; }
    public string QTGIRODIA { get; set; }
    public string PERCEVOLUCAOVENDA { get; set; }
    public string VLVENDMESANT { get; set; }
    public string VLCUSTOMESFINANT { get; set; }
    public string VLCUSTOMESREALANT { get; set; }
    public string NUMNOTAULTENT { get; set; }
    public string PCOMPRAULTENT { get; set; }
    public string VLSTULTENT { get; set; }
    public string MODULO { get; set; }
    public string RUA { get; set; }
    public string APTO { get; set; }
    public string DTULTINVENT { get; set; }
    public string CUSTODOLAR { get; set; }
    public string CUSTOULTENTMED { get; set; }
    public string VALORULTENTMED { get; set; }
    public string QTRESERVMED { get; set; }
    public string QTREQUISICAO { get; set; }
    public string CUSTOREALSEMST { get; set; }
    public string DTULTPEDCOMPRA { get; set; }
    public string CUSTOULTPEDCOMPRA { get; set; }
    public string CUSTOULTENTFIN { get; set; }
    public string DTULTDESDOBRA { get; set; }
    public string CORREDOR { get; set; }
    public string QTLOJA { get; set; }
    public string BASEBCR { get; set; }
    public string STBCR { get; set; }
    public string CUSTOPROXIMACOMPRA { get; set; }
    public string NUMTRANSENTULTENT { get; set; }
    public string CUSTOULTENTANT { get; set; }
    public string MOTIVOBLOQESTOQUE { get; set; }
    public string CODDEVOL { get; set; }
    public string ESTMAX { get; set; }
    public string QTDEVOLMES { get; set; }
    public string QTDEVOLMES1 { get; set; }
    public string QTDEVOLMES2 { get; set; }
    public string QTDEVOLMES3 { get; set; }
    public string CUSTOULTENTLIQ { get; set; }
    public string CUSTOREALLIQ { get; set; }
    public string VLULTENTCONTSEMST { get; set; }
    public string MODULOCX { get; set; }
    public string RUACX { get; set; }
    public string APTOCX { get; set; }
    public string DTULTALTERSRVPRC { get; set; }
    public string DTPRIMCOMPRA { get; set; }
    public string ESTIDEAL { get; set; }
    public string DTULTFAT { get; set; }
    public string VLULTPCOMPRA { get; set; }
    public string CUSTONFSEMST { get; set; }
    public string BASEICMSULTENT { get; set; }
    public string CUSTOULTENTCONT { get; set; }
    public string QTTRANSITO { get; set; }
    public string VLSTGUIAULTENT { get; set; }
    public string CUSTONFSEMSTGUIAULTENT { get; set; }
    public string IVAULTENT { get; set; }
    public string ALIQICMS1ULTENT { get; set; }
    public string ALIQICMS2ULTENT { get; set; }
    public string REDBASEIVAULTENT { get; set; }
    public string PERCICMSFRETEFOBSTULTENT { get; set; }
    public string VLFRETECONHECULTENT { get; set; }
    public string PERCALIQEXTGUIAULTENT { get; set; }
    public string QTESTORNOPRODUZDIA { get; set; }
    public string QTESTORNOPRODUZMES { get; set; }
    public string QTPRODUZIDADIA { get; set; }
    public string QTPRODUZIDAMES { get; set; }
    public string BASEICMSULTENTTAB { get; set; }
    public string VLSTULTENTTAB { get; set; }
    public string VLSTGUIAULTENTTAB { get; set; }
    public string CUSTONFSEMSTTAB { get; set; }
    public string CUSTONFSEMSTGUIAULTENTTAB { get; set; }
    public string IVAULTENTTAB { get; set; }
    public string ALIQICMS1ULTENTTAB { get; set; }
    public string ALIQICMS2ULTENTTAB { get; set; }
    public string REDBASEIVAULTENTTAB { get; set; }
    public string PERCICMSFRETEFOBSTULTENTTAB { get; set; }
    public string VLFRETECONHECULTENTTAB { get; set; }
    public string PERCALIQEXTGUIAULTENTTAB { get; set; }
    public string PERCMVAORIGULTENT { get; set; }
    public string PERCMVAORIGTAB { get; set; }
    public string ASSINATURA { get; set; }
    public string ROTINALANC { get; set; }
    public string DTALTERACAO1107 { get; set; }
    public string DTEMISSAOULTENT { get; set; }
    public string QTGIROCURVATURA { get; set; }
    public string QTGIROCURVATURAANT { get; set; }
    public string CUSTOFORNEC { get; set; }
    public string QTFRENTELOJA { get; set; }
    public string NUMFCI { get; set; }
    public string VLPARCELAIMPFCI { get; set; }
    public string PERCCONTEUDOIMPFCI { get; set; }
    public string VLIMPORTACAOFCI { get; set; }
    public string CUSTOFORNECSEMST { get; set; }
    public string CUSTOPROXIMACOMPRASEMST { get; set; }
    public string CUSTOFINSEMST { get; set; }
    public string CUSTOULTENTFINSEMST { get; set; }
    public string CUSTOULTENTSEMST { get; set; }
    public string CUSTOULTPEDCOMPRASEMST { get; set; }
    public string BASEIPIULTENT { get; set; }
    public string VLIPIULTENT { get; set; }
    public string PERCIPIULTENT { get; set; }
    public string QTTRANSITOTV13 { get; set; }
    public string CODCEST { get; set; }
    public string IDENTIFICADOR { get; set; }
    public string TEMESTOQUEECOMMERCE { get; set; }
    public string QTINDUSTRIA { get; set; }
    public string VLFCPICMSULTENTTAB { get; set; }
    public string VLFCPSTULTENTTAB { get; set; }
    public string VLBASEFCPSTULTENTTAB { get; set; }
    public string VLBCFCPSTRET { get; set; }
    public string PERFCPSTRET { get; set; }
    public string VLFCPSTRET { get; set; }
    public string PERCREDBASEEFET { get; set; }
    public string VLBASEEFET { get; set; }
    public string PERCICMSEFET { get; set; }
    public string VLICMSEFET { get; set; }
    public string NUMTRANSULTENTET { get; set; }
    public string NUMTRANSULTENTED { get; set; }
    public string ALIQICMS1 { get; set; }
    public string NUMTRANSULTENTST { get; set; }
    public string ESTBONIFIC { get; set; }
    public string VLICMSBCR { get; set; }
    public string BASEICMSBCR { get; set; }
    public string NUMERO_AUX { get; set; }
    public string NUMERO { get; set; }
    public string ALIQICMS1RET { get; set; }
    public string TIPOCURVA { get; set; }
    public string CURVA { get; set; }
    public string SUBCURVA { get; set; }
    public string FREQUENCIA { get; set; }
    public string NUMTRANSENTULTENTBNF { get; set; }
    public string NUMEROCX { get; set; }
    public string QTCROSSDOCK { get; set; }
    public string NUMEROCX_AUX { get; set; }
    public string QTESTOQUEEMTERCEIRO { get; set; }
    public string QTESTOQUEDETERCEIRO { get; set; }
    public string QTTRANSITOTV10 { get; set; }
    public string DTHORAULTSAIDA { get; set; }
    public string DTHORAULTALTDISP { get; set; }
    public string QBCMONORET { get; set; }
    public string ADREMICMSRET { get; set; }
    public string VICMSMONORET { get; set; }
    public string CUSTOULTENTFISCAL { get; set; }
    public string CUSTOFISCAL { get; set; }
    public string VLIPISUSPENSOULTENT { get; set; }
    public string VLIISUSPENSOULTENT { get; set; }
    public string PLIQULTENT { get; set; }
}